domain: NZ-based B2C iOS app startup that is pre product-market-fit
perspective: bootstrapped founder, who successfully navigated pre-PMF phase with limited
  capital with a successful exit
user_role: Solo Founder
